spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/LR2
    username: user_all
    password: "1234"

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        id.new_generator_mappings: false

server:
  port: 8080

